name: DutchyTpaZhTw
main: dev.jonz94.dutchytpazhtw.Tpa
version: 1.0.0
api-version: 1.16
author: jonz94
description: A simple TPA plugin
commands:
  tpa:
    description: TPA to a player
  tpaccept:
    description: Accept a TPA request
  tpdeny:
    description: Deny a TPA request
  tpyes:
    description: Alias for /tpaccept
  tpno:
    description: Alias for /tpdeny
